package drj.euler.problems;

import java.util.NavigableSet;
import java.util.TreeSet;

import drj.euler.Answer;
import drj.euler.Problem;
import drj.euler.Utility;

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten
 * pentagonal numbers are:
 * 
 * <p>		1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * <p>It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
 * difference, 70  22 = 48, is not pentagonal.
 * 
 * <p>Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk - Pj| is minimized; what is the value
 * of D?
 */
@Answer("5482660")
public class Problem044 extends Problem {

	public static void main(String[] args) {
		Problem p = new Problem044();
		System.out.println(p);
	}

	@Override
	protected String onSolve() {
		NavigableSet<Long> pentagonals = new TreeSet<Long>();
		pentagonals.add(1L);

		int nth = 2;
		long minDifference = Long.MAX_VALUE;

		while (Utility.getPentagonal(nth) - Utility.getPentagonal(nth - 1)
				< minDifference) {
			Long pentagonal = Utility.getPentagonal(nth++);
			pentagonals.add(pentagonal);
			for (long num : pentagonals.subSet(
					pentagonals.ceiling(pentagonal - minDifference)
					, pentagonals.last())) {
				if (Utility.isPentagonal(pentagonal - num)
						&& Utility.isPentagonal(pentagonal + num)
						&& pentagonal - num < minDifference) {
					minDifference = pentagonal - num;
				}
			}
		}

		return String.valueOf(minDifference);
	}
}
